### ISSUE TITLE
Supported Heat Pumps Megathread

### ISSUE THREAD

**Issue by KazWolfe** [muart-group/muart-group.github.io#1]
Do you have a heat pump that works but isn't [on the supported unit list](https://muart-group.github.io/user/supported)? Give us some information about it here!

When submitting a heat pump report, please include the unit model number, whether it's part of a branch box system, the connect response from the log (see screenshot), as well as any findings that you may think are relevant.

![image](https://github.com/muart-group/muart-group.github.io/assets/5192145/d2dd7637-fd28-48f2-9ac4-5f93ba20ee0d)

While not required, we'd highly prefer you use the template below. Please note that project maintainers reserve the right to edit your submission with additional information.

```md
**Model Number:**
**Branch Box?:** Yes / No
**Connect Response:** `[Connect Response Hex Here]`

**Notes:**
- I think this is a neat template!
```

**Comment by Olgmo** [comment]
**Model Number: **
   Mitsubishi Kaiteki - MSZ-LN35VGW
**Connect Response:** 
   `[FC.7B.01.30.10]C9.03.00.20.00.14.07.F5.8C.25.A0.BE.94.BE.A0.BE 89`
**Notes:**
   Seems to work okay :-)

**Comment by awkaplan** [comment]
**Model Number: **
MLZ-KP09NA

**Branch Box?:** Yes

**Connect Response:** `[FC.7B.01.30.10]C9.03.00.20.00.14.07.65.84.25.A0.BE.94.BE.A0.BE 21`

**Notes:**
Works with MKH2 thermostat (12v lines bridged) on a HiLetgo Mini ESP-WROOM-32.  However, all sensors appear to be disabled.  Example config:

```
uart:
  - id: hp_uart
    baud_rate: 2400
    parity: EVEN
    rx_pin:
      number: GPIO17
    tx_pin:
      number: GPIO16
  - id: ts_uart
    baud_rate: 2400
    parity: EVEN
    rx_pin:
      number: GPIO21
    tx_pin:
      number: GPIO22

climate:
  - platform: mitsubishi_itp
    uart_heatpump: hp_uart
    uart_thermostat: ts_uart
```

**Comment by hadleyrich** [comment]
**MFZ-KW50VG (RapidHeat KW50 Floor Console):**
**Branch Box?:** No
**Connect Response:** `Capabilities Response: [FC.7B.01.30.10]C9.03.00.20.00.14.07.F5.8C.25.A0.BE.94.BE.A0.BE 89`

**Notes:**
- I think this is a neat template. Nice work on the component!
- Series has no horizontal vanes
- Compressor frequency not available

Pretty cool to see how far this stuff has come. I originally hacked the protocol back in 2016, which is what the Arduino library was based on (https://web.archive.org/web/20171007190023/https://nicegear.co.nz/blog/hacking-a-mitsubishi-heat-pump-air-conditioner/). I remember sitting in my office with a logic analyzer poking things and prodding the thermistor etc. Things are much more convenient now with all the cheap tiny ESP32 boards with all their functionality!

UART Config:
```
uart:
  - id: hp_uart
    baud_rate: 2400
    parity: EVEN
    rx_pin:
      number: GPIO26
    tx_pin:
      number: GPIO32
```
